[package]
name = "taplo-wasm"
version = "0.1.0"
edition = "2021"
publish = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
crate-type = ["cdylib"]

[dependencies]
anyhow = "1.0.57"
async-trait = "0.1.56"
clap = { version = "3.1.18", features = ["derive"] }
console_error_panic_hook = "0.1.7"
futures = "0.3.21"
js-sys = "0.3.57"
lsp-async-stub = { path = "../lsp-async-stub" }
serde = { version = "1.0.137", features = ["derive"] }
serde_json = "1.0.81"
taplo = { path = "../taplo" }
taplo-cli = { path = "../taplo-cli", optional = true }
taplo-common = { path = "../taplo-common" }
taplo-lsp = { path = "../taplo-lsp", optional = true }
time = { version = "0.3.9", features = ["parsing"] }
tokio = "1.19.2"
tracing = "0.1.35"
url = "2.2.2"
wasm-bindgen = { version = "0.2.80", features = ["serde-serialize"] }
wasm-bindgen-futures = "0.4.30"
indexmap = "~1.6"

[features]
default = ["lsp", "cli"]
cli = ["taplo-cli"]
lsp = ["taplo-lsp"]

[profile.release]
opt-level = 's'
lto = true
