[package] # Cargo.toml(1, 2): table "package" here
name    = "uuid"
version = "0.1.0"

[dependencies.renamed_example]
version = "0.1.0"
package = "example" # entry conflicts with table Even Better TOML