name: Continuous integration

on:
  push:
    branches:
      - master
    tags:
      - release-*
    paths-ignore:
      - "site/**/*"
      - schemas/**/*
      - util/**/*
  workflow_dispatch: {}
  pull_request:
    branches:
      - master

jobs:
  auto_tag:
    name: Tag Releases
    if: (github.event_name == 'push' && github.ref_type == 'branch') || github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.WORKFLOW_PAT }}
          fetch-depth: 0
      - uses: tamasfe/auto-tag@v5
        with:
          name: tamasfe
          email: me@tamasfe.dev
          token: ${{ secrets.WORKFLOW_PAT }}

  test:
    name: Test on Rust stable
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install latest Rust toolchain
        run: rustup update --no-self-update
      - uses: Swatinem/rust-cache@v2
      - name: Test Taplo
        run: |
          cargo test -p taplo

  check_wasm32:
    name: Check on WASM
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install latest Rust toolchain
        run: |
          rustup update --no-self-update
          rustup target add wasm32-unknown-unknown
      - uses: Swatinem/rust-cache@v2
      - working-directory: crates/taplo-wasm
        run: cargo check --target wasm32-unknown-unknown

  toml_test:
    name: Run toml-test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install latest Rust toolchain
        run: |
          rustup update --no-self-update
      - uses: Swatinem/rust-cache@v2
      - name: Retrieve toml-test
        run: |
          wget https://github.com/BurntSushi/toml-test/releases/download/v1.1.0/toml-test-v1.1.0-linux-amd64.gz
          gunzip toml-test-v1.1.0-linux-amd64.gz
          chmod +x toml-test-v1.1.0-linux-amd64
      - name: Build taplo-cli
        run: |
          cargo build --bin taplo --no-default-features --features "rustls-tls,toml-test"
      - name: Run toml-test
        run: ./toml-test-v1.1.0-linux-amd64 ./target/debug/taplo -- toml-test

  test-msrv-lib:
    name: Test libraries with MSRV
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install latest Rust toolchain
        run: |
          rustup update --no-self-update
          rustup default 1.67
      - uses: Swatinem/rust-cache@v2
      - name: Test crates
        run: |
          cargo +1.67 check -p lsp-async-stub -p taplo-common -p taplo-lsp -p taplo
          cargo +1.67 test -p lsp-async-stub -p taplo-common -p taplo-lsp -p taplo

  test-msrv-bin:
    name: Test binaries with MSRV
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install latest Rust toolchain
        run: |
          rustup update --no-self-update
          rustup default 1.74
          rustup target install wasm32-unknown-unknown
      - uses: Swatinem/rust-cache@v2
      - name: Test taplo-cli
        run: |
          cargo +1.74 check -p taplo-cli
          cargo +1.74 test -p taplo-cli
      - name: Test taplo-wasm
        working-directory: crates/taplo-wasm
        run: |
          cargo +1.74 check

