name: Continuous integration

on:
  push:
    branches:
      - master
    tags:
      - release-*
    paths-ignore:
      - "site/**/*"
      - schemas/**/*
      - util/**/*
  workflow_dispatch: {}
  pull_request:
    branches:
      - master

jobs:
  auto_tag:
    name: Tag Releases
    if: (github.event_name == 'push' && github.ref_type == 'branch') || github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.WORKFLOW_PAT }}
          fetch-depth: 0
      - uses: tamasfe/auto-tag@v5
        with:
          name: tamasfe
          email: me@tamasfe.dev
          token: ${{ secrets.WORKFLOW_PAT }}

  test:
    name: Test on Rust stable
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      - uses: Swatinem/rust-cache@v1
      - uses: actions-rs/cargo@v1
        name: Test Taplo
        with:
          command: test
          args: -p taplo

  check_wasm32:
    name: Check on WASM
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          target: wasm32-unknown-unknown
          toolchain: stable
          override: true
      - uses: Swatinem/rust-cache@v1
      - working-directory: crates/taplo-wasm
        run: cargo check --target wasm32-unknown-unknown

  toml_test:
    name: Run toml-test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      - uses: Swatinem/rust-cache@v1
      - name: Clippy
        run: cargo clippy --all-features --all-targets -- -D warnings
      - name: Format
        run: cargo fmt -- --check
      - name: Retrieve toml-test
        run: |
          wget https://github.com/BurntSushi/toml-test/releases/download/v1.1.0/toml-test-v1.1.0-linux-amd64.gz
          gunzip toml-test-v1.1.0-linux-amd64.gz
          chmod +x toml-test-v1.1.0-linux-amd64
      - uses: actions-rs/cargo@v1
        name: Build taplo-cli
        with:
          command: build
          args: --bin taplo --no-default-features --features "rustls-tls,toml-test"
      - name: Run toml-test
        run: ./toml-test-v1.1.0-linux-amd64 ./target/debug/taplo -- toml-test
